# Generated by Django 4.1.4 on 2023-06-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('IFSC', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Distict', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('BName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
            ],
        ),
    ]
