# Generated by Django 4.1.4 on 2023-06-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='BName',
            new_name='Bank',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='Distict',
            new_name='District',
        ),
    ]
