# Generated by Django 4.1.4 on 2023-06-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_bname_bank_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Branch',
            new_name='Branches',
        ),
    ]
