# Generated by Django 4.1.4 on 2023-06-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_branch_branch_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='BName',
            new_name='Bank',
        ),
    ]
